### ISSUE TITLE
Update input field width using any trigger

### ISSUE THREAD

**Issue by Wenape** [MartinF/jQuery.Autosize.Input#1]
Is it possible to update the width of the input field apart from pressing 'keyup' or 'keydown' while focusing on the input field?

The thing is, I have an auto-complete plugin which allows you to select a suggestion. This suggestion then appears as text on the input field. The thing is that you have to 'focus' on the text field and then press a key for the width to 'update' to the length of the suggestion.

It is possible to run an 'update' function that I could bind with clicking on the auto-complete suggestion?

**Comment by MartinF** [comment]
There is an update() method on the object which you can call to update the width.
