### ISSUE TITLE
Getting errors on compile

### ISSUE THREAD

**Issue by jtrees** [MartinF/jQuery.Autosize.Input#10]
I'm new to TypeScript so I might be doing something blatantly wrong but I'm currently getting errors when I compile jquery.autosize.input.ts. I'm using TypeScript version 0.9.5 on Windows 8.1. Here's what I get:

```
$ tsc jquery.autosize.input.ts
jquery.autosize.input.ts(48,29): error TS1005: ';' expected.
jquery.autosize.input.ts(48,30): error TS1003: Identifier expected.
```

Removing the brackets, results in the following:

```
$ tsc jquery.autosize.input.ts
jquery.autosize.input.ts(51,10): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
jquery.autosize.input.ts(56,17): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
jquery.autosize.input.ts(96,10): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
jquery.autosize.input.ts(99,10): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
```

Very well then. Let's target ECMAScript 5:

```
$ tsc --target ES5 jquery.autosize.input.ts
jquery.d.ts(23,13): error TS2095: Could not find symbol 'bool'.
jquery.d.ts(25,13): error TS2095: Could not find symbol 'bool'.
jquery.d.ts(31,19): error TS2095: Could not find symbol 'bool'.
[...]
jquery.autosize.input.ts(35,5): error TS2011: Cannot convert 'JQuery' to 'string'.
```

What gives?

**Comment by MartinF** [comment]
I hadn't noticed that a new release of TypeScript is out before you mentioned that you have 0.9.5. 
I will try to install the latest version tomorrow (it is 4.24 AM here right ow) :)

Maybe they have changed something in the new release. 
I also had problems when switching from 0.8.X to 0.9.1.

**Comment by MartinF** [comment]
This have been fixed and I have just confirmed it also compiles against TypeScript version 1.0.
However ES3 is not supported, but I would consider changing it to work if people need it (I don't have the need for it myself).
