### ISSUE TITLE
How to pass options when calling function.

### ISSUE THREAD

**Issue by bergonom** [MartinF/jQuery.Autosize.Input#11]
I tried 

```
$('input[type="text"]').autosizeInput( {space: 1} )
```

But it doesn't work.

I can't find an example - except for the one using data attributes - anywhere.

Thanks.

**Comment by subhog** [comment]
I've tried the same with a similar problem.

I've added logging after [this line](https://github.com/MartinF/jQuery.Autosize.Input/blob/master/jquery.autosize.input.js#L84), and `options` were defined.

However, logging after [this line](https://github.com/MartinF/jQuery.Autosize.Input/blob/master/jquery.autosize.input.js#L90) showed that the options were undefined now, and hence default options were used to initialize the plugin.
