### ISSUE TITLE
Add ability to set space option globally

### ISSUE THREAD

**Issue by adamcharnock** [MartinF/jQuery.Autosize.Input#15]
Having the ability to set a global default for the space option would be a very big help in my case.

Thanks for the plugin though, just what I needed :-)

**Comment by MartinF** [comment]
Thanks for the feedback.
I have just implemented this feature. It can be set through Plugins.AutosizeInput.getDefaultOptions().space = 123; 

Remember it needs to be set before the plugin initializes.

http://jsfiddle.net/mJMpw/617/
