### ISSUE TITLE
Doesn't work when new input is inserted

### ISSUE THREAD

**Issue by Alphazork** [MartinF/jQuery.Autosize.Input#25]
When the website is fully loaded and I insert a new input with jquery before() it doesn't reize

**Comment by jeremyblaze** [comment]
You probably just need to re-run the function when you add the new field.

**Comment by MartinF** [comment]
Yes, that or look at the bottom where I have commented out some code that uses the .on() function which automatically initializes the plugin on focus.

**Comment by MartinF** [comment]
See - https://github.com/MartinF/jQuery.Autosize.Input/issues/19
