### ISSUE TITLE
doesn't work in IE 8 or IE 10

### ISSUE THREAD

**Issue by ozyn** [MartinF/jQuery.Autosize.Input#3]
Great plug-in, works fine in FF and IE 9.

**Comment by MartinF** [comment]
I haven't tested it in IE8 as I only support IE9+.
IE 10 works fine for me.

**Comment by ozyn** [comment]
you're right, thanks for checking.

On Sat, Aug 10, 2013 at 4:59 AM, Martin From notifications@github.comwrote:

> I haven't tested it in IE8 as I only support IE9+.
> IE 10 works fine for me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MartinF/jQuery.Autosize.Input/issues/3#issuecomment-22438560
> .

## 

## Thanks.

Olivier Zyngier
olivier@mandosoft.com
http://www.mandosoft.com
