### ISSUE TITLE
can you add a license so we know how to use it

### ISSUE THREAD

**Issue by ozyn** [MartinF/jQuery.Autosize.Input#4]
e.g. MIT would be great.

**Comment by MartinF** [comment]
Done :)

**Comment by ozyn** [comment]
the license.md file should have your name and the copyright year. Even better, I'd suggest adding the copyright notice with the date and name to the source code directly.

**Comment by MartinF** [comment]
Hey, thanks again.
Just added year and name.
I don't care much about the license stuff, I put the code here for anybody to use it.
I just hope people contribute back with fixes and improvements if they make any.

**Comment by ozyn** [comment]
thanks, it'll help.
If we make any additions or fixes I'll be sure to pass them on to you.

On Mon, Aug 19, 2013 at 2:09 PM, Martin From notifications@github.comwrote:

> Hey, thanks again.
> Just added year and name.
> I don't care much about the license stuff, I put the code here for anybody
> to use it.
> I just hope people contribute back with fixes and improvements if they
> make any.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MartinF/jQuery.Autosize.Input/issues/4#issuecomment-22904443
> .

## 

## Thanks.

Olivier Zyngier
olivier@mandosoft.com
http://www.mandosoft.com

**Comment by ozyn** [comment]
contribution: on line 16 you may want to use on() rather than bind(), if
you're going with jQuery 1.8+ compatibility.

On Mon, Aug 19, 2013 at 2:09 PM, Martin From notifications@github.comwrote:

> Hey, thanks again.
> Just added year and name.
> I don't care much about the license stuff, I put the code here for anybody
> to use it.
> I just hope people contribute back with fixes and improvements if they
> make any.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MartinF/jQuery.Autosize.Input/issues/4#issuecomment-22904443
> .

## 

## Thanks.

Olivier Zyngier
olivier@mandosoft.com
http://www.mandosoft.com

**Comment by MartinF** [comment]
Thanks.
on() is already being used. 
The change was commited 8 days ago.

https://github.com/MartinF/jQuery.Autosize.Input/blob/master/jquery.autosize.input.js
