### ISSUE TITLE
autosize inputs when filled in by javascript

### ISSUE THREAD

**Issue by ozyn** [MartinF/jQuery.Autosize.Input#5]
The inputs don't grow when filled in by javascript. Here is an example (sorry for the bad readability, I had to remove all code that prevents the actual display in this page):

.... script ...
    $(document).ready(function() {
        $(".autosizeInput").data('autosize-input' , {"space":8}).autosizeInput();
    });

```
var addInputCounter = 0;
function addTextToInput()
{
    $('#autosizeInput1').val($('#autosizeInput1').val() + " --" + (++addInputCounter) + ": " + "text added here"); 
    return false;
}
```

.... page ....
input type="text" value="" id="autosizeInput1" class="autosizeInput" placeholder="Autosize" 
a href="#" onClick="addTextToInput();"

**Comment by MartinF** [comment]
There is an update() method on the autosizeinput object you can call to make it update when the value has changed. 

To get the autosizeinput instance and update it you can do like this in your example
$('#autosizeInput1').val($('#autosizeInput1').val() + " --" + (++addInputCounter) + ": " + "text added here").data(Plugins.AutosizeInput.instanceKey).update();

As far as I know there isn't a cross-browser event that makes it possible to listen for programmatical changes of the value of an input.
The only option is to use a timer/interval and keep polling to check if the value has changed and update if it has.
I could implement this, but so far I have left it out as it seems pretty simple to call the update() method when needed. 
See http://stackoverflow.com/a/1848414/58524 for a possible solution.
