### ISSUE TITLE
not working in wordpress

### ISSUE THREAD

**Issue by flatcat** [MartinF/jQuery.Autosize.Input#6]
hello when i try to get this script work on wordpress i get error:

var Plugins;
(function (Plugins) {
    var AutosizeInput = (function () {
        function AutosizeInput(input, options) {
            var _this = this;
Uncaught TypeError: Property '$' of object [object Object] is not a function 
            this._options = options;

i use 
jQuery(document).ready(function($){
$(".some class").autosizeInput();
});

thanks for help

**Comment by MartinF** [comment]
Do you have it online anywhere?
Just to make sure, do you include it after the jquery library?
