### ISSUE TITLE
Object doesn't support this action

### ISSUE THREAD

**Issue by panil21** [MartinF/jQuery.Autosize.Input#7]
In IE8, it shows me an error. The error was "Object.defineProperty(..."

How to correct this.

**Comment by MartinF** [comment]
I would suspect that this could have something to do with the JQuery version.
If you are using jQuery +2.0 then IE8 is no longer supported. You would have to use a 1.x version to have IE8 support.

**Comment by roryf** [comment]
`Object.defineProperty` is nothing to do with jQuery https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Internet_Explorer_8_specific_notes

**Comment by MartinF** [comment]
I can see what the problem is. 
The TypeScript compiler use Object.defineProperty which makes it not work properly in IE8.

**Comment by MartinF** [comment]
Before i Close I just want to mention than compiling the typescript to ECMA 3 would probably not have cause this problem, if you need support for older browsers.

**Comment by GermainBergeron** [comment]
It seems that compiling for ES3 don't work.  See the error below :

error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.

**Comment by MartinF** [comment]
Yes, as previously pointed out, it is because Object.defineProperty is used to declare the properties which is not supported in ES3. It could easily be rewritten to support ES3 by replacing all properties with regular functions.

I don't know if there is any big need for this, as I have no need for it myself as I only target newer browsers in my work.

**Comment by MartinF** [comment]
Please let me know if it would be a good idea to support ES3. 

As mentioned I have no need for it myself, but if there is a demand for it I will make the change.

**Comment by MartinF** [comment]
I just removed all properties.
